### ISSUE TITLE
add_inspire_categories is completely broken

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspire-dojson#114]
reviewing the uses of `classify_field`, I discovered this: https://github.com/inspirehep/inspire-dojson/blob/a37eaa72cde753eaf828e41db96297d3fe25fe2e/inspire_dojson/hep/model.py#L51-L65

It is completely broken as:
1. `inspire_category` does not exist in the schema (`inspire_categories` is the correct form);
2. it overwrites the output on every iteration.

I don't know if it is ever run, as it requires `arxiv_eprints` to be present but `inspire_categories` not to be, which should be pretty rare, and I have never seen any migration error because of this field.

It would be good to review the whole logic around categories in dojson as it's quite intricate.

**Comment by jacquerie** [comment]
Interestingly enough, that line is **never** called in the entire test suite: https://coveralls.io/builds/13627440/source?filename=inspire_dojson%2Fhep%2Fmodel.py#L58.

**Comment by jacquerie** [comment]
Closed in https://github.com/inspirehep/inspire-dojson/pull/115.
