### ISSUE TITLE
missing test dependencies

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspire-dojson#18]
After installing in a clean environment, the following dependencies were missing to run the tests (besides those installed by `pip install -e .`:
`pytest, pytest-coverage, pytest-flake8`.

**Comment by jacquerie** [comment]
You'll want to install them with `pip install -e .[tests]`, like Travis does: https://github.com/inspirehep/inspire-dojson/blob/d22c0098a2539d035af48688064787bacc690363/.travis.yml#L43
