### ISSUE TITLE
'authors.full_name' should be unicode

### ISSUE THREAD

**Issue by chris-asl** [inspirehep/inspire-dojson#195]
There might be a discrepancy on what type the `full_name` has when it leaves `dojson`. 

#### Why
Well, firstly from @iulianav 's PR and the discussion [here](https://github.com/inspirehep/inspire-next/pull/3064#discussion_r161750708) we got the first idea that this is happening (with her latest commit).  

Secondly, after a discussion with @jacquerie IRL, we had the impression that it was `inspire_utils.name::normalize_name` that had the issue.

But then in [this commit](https://github.com/inspirehep/inspire-utils/pull/39/commits/60f1ad1f9bee107e97bc7530ceebfd1a89c13a1c), after I converted all string literals in the `expected_name` from `str` to `unicode`, all the tests pass (without me having to change anythin in the `name` module, which means that `normalize_name` does return `unicode`.

**Comment by michamos** [comment]
This problem is not related to `inspire-dojson`, and will be fixed directly in https://github.com/inspirehep/inspire-next/pull/3064.
