### ISSUE TITLE
dojson: corrigendum

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-dojson#31]
https://sentry.cern.ch/inspire-sentry/inspire-labs/group/822798/

Records with `material` `corrigendum`:
```
<datafield tag="024" ind1="7" ind2=" ">
    <subfield code="2">DOI</subfield>
    <subfield code="q">Corrigendum</subfield>
    <subfield code="9">bibmatch</subfield>
    <subfield code="a">10.1016/j.physletb.2014.05.010</subfield>
</datafield>
```

should be conflated into `erratum` (see also https://github.com/inspirehep/inspire-schemas/pull/195#issuecomment-313367954)

**Comment by jacquerie** [comment]
As mentioned by @michamos in https://sentry.cern.ch/inspire-sentry/inspire-labs/group/822798/, no need to handle this in DoJSON as this was affecting exactly two records, which were since corrected.
