### ISSUE TITLE
refextract: texkey extraction

### ISSUE THREAD

**Issue by annetteholtkamp** [inspirehep/inspire-dojson#41]
refextract extracts texkeys from pdf. These texkeys are the ones used by the author and are not necessarily Inspire texkeys. So the syntax of the extracted texkeys need to be checked before adding them.

**Comment by jacquerie** [comment]
CC: @michamos

**Comment by michamos** [comment]
after discussing on standup with the other labs today, we decided that this is not a problem for anything.
