### ISSUE TITLE
hep: don't normalize again names in references

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire-dojson#69]
See: https://github.com/inspirehep/inspire-dojson/blob/d1524e2f85a98e10ed5db2f508a44cb933f0ecc5/tests/test_hep_bd9xx.py#L808-L864

**Comment by michamos** [comment]
this should be fixed in the reference builer, by using `normalize_name`.

**Comment by ammirate** [comment]
`normalize_name` where is defined?

**Comment by michamos** [comment]
`normalize_name` in `inspire_schemas.utils` you shall find.

**Comment by ammirate** [comment]
`normalize_author_name` :1st_place_medal:
